### ISSUE TITLE
Prefix for my character??

### ISSUE THREAD

**Issue by Crispyrox** [henry232323/RPGBot-V2-Issue-Tracker#11]
You said In the tutorial that I can set a prefix for my character... what are the commands for that? I've looked everywhere!!

**Comment by henry232323** [comment]
The prefix is set during character creation or editing. rp!c edit

**Comment by Crispyrox** [comment]
> The prefix is set during character creation or editing. rp!c edit

It wont let me create a character, it said I have to upload it from Beyond..

**Comment by henry232323** [comment]
> > The prefix is set during character creation or editing. rp!c edit
> 
> It wont let me create a character, it said I have to upload it from Beyond..

Can you show me what you mean?

**Comment by Crispyrox** [comment]
> > > The prefix is set during character creation or editing. rp!c edit
> > 
> > 
> > It wont let me create a character, it said I have to upload it from Beyond..
> 
> Can you show me what you mean?
It says nothing about how to set the prefix in the tutorial
![Screenshot_2020-11-29-00-46-01-053](https://user-images.githubusercontent.com/59496145/100537326-5abf8880-31dc-11eb-819a-fe8f810dfe25.jpg)

**Comment by Crispyrox** [comment]
Nevermind! Went through and found it sorry for the trouble!
