### ISSUE TITLE
Images do not display when viewing a character

### ISSUE THREAD

**Issue by delwyrn** [henry232323/RPGBot-V2-Issue-Tracker#16]
When setting an image URL during the character creation or editing process, the image displays perfectly fine. After saving and viewing my character sheet, the image will not show :( This is not a problem with the item sheet, as images do display upon viewing my items. I know it's not a problem with the image I'm using (I tested multiple different images) and I know it's not a size restriction problem (images still show up on items when the description hits maximum character limit but never in the character sheet, even when the description is empty). Please let me know if you want me to send over some example screenshots, and thank you for the amazing and detailed bot! :)

**Comment by henry232323** [comment]
At the moment, images need to be added to the shown attributes list to be displayed, these should be enabled by default, so we will need to fix this.

**Comment by delwyrn** [comment]
Thank you for the quick response!
