### ISSUE TITLE
pause reaction is not actually pausing timeout on character creation

### ISSUE THREAD

**Issue by nacjm** [henry232323/RPGBot-V2-Issue-Tracker#30]
When using the pause reaction to pause the timer when creating a character, the menu will still timeout after a few moments

**Comment by Potzerus** [comment]
intended behaviour, pause is for pausing the deletion and reading of your inputs, not for delaying or bypassing menu timeout

**Comment by nacjm** [comment]
Ohhh. That is not what I had originally thought it was for. My mistake then.
