### ISSUE TITLE
Multiple Attribute abilities give an error on creation 

### ISSUE THREAD

**Issue by nacjm** [henry232323/RPGBot-V2-Issue-Tracker#32]
see screenshot: 
![image](https://user-images.githubusercontent.com/7560033/132406854-e17e343b-e165-4d9e-b0c9-34b344c2bc3f.png)

**Comment by Potzerus** [comment]
Error report
https://discord.com/channels/303307934774067210/867927286060560394/884893520731730031

**Comment by nacjm** [comment]
Henry and I debugged and solved this, closing issue for now.
