### ISSUE TITLE
Item Images not loading, still load as icons

### ISSUE THREAD

**Issue by crux-f** [henry232323/RPGBot-V2-Issue-Tracker#62]
Hello there,
 
This is a fine bot and I have had a great time using it to create trading cards on my little Discord server, by linking card images to items in this system. However recently, the images have stopped loading; They still appear as the tiny icon in the top left, however.

The strange thing is, this issue is rather inconsistent; It only seems to happen on occasion, and until now has cleared up on its own without any prodding after a few hours or so.

However, it seems to now have stopped entirely; It's been 3 days, and the issue still doesn't seem to want to clear up.

I will update this issue if it does so, however I thought it was a significant enough problem at this point that it was worth reporting.
![broken item](https://user-images.githubusercontent.com/5208142/150410440-b00582cf-58a8-41bc-b124-d160849620a0.PNG)

Attached is an example of the item loading the icon, but not the full image.

Let me know if you need any more information,

Thanks!

**Comment by crux-f** [comment]
Update: This issue is still persisting; Images load around 50% of the time, and only some items seem affected.

**Comment by henry232323** [comment]
In general, this seems to be an issue on Discord's end, and can be caused by the source image URL getting deleted, such as if it was uploaded in a Discord message then the message deleted
